### ISSUE TITLE
CentOS ModuleNotFoundError

### ISSUE THREAD

**Issue by sw23pdx** [NGSolve/ngsolve#16]
I'm running CentOS Linux release 7.6.1810 (Core) on a HPC cluster. I followed the Build On Linux page's directions and the prerequisites are installed on the system. I'm using Python 3.6.4 (compiled by gcc 6.3.0), gcc 8.2.0, CMake 3.14.5, and openMPI 2.0 (compiled by gcc 8.2.0). The last "To start mpi shell call" and beyond is from me trying to open the Solve > Python Shell in the GUI. The NGSolve install directory is /vol/apps/test/ngsolve/gcc-8.2.0/ . I get the below dialogue as well as not being able to load Python scripts into NGSolve too. I think there is something funky going on with my $PYTHONPATH variable, if I try to add a path to lib/python3.6/site-packages on either end of $PYTHONPATH, it throughs the below _tkinter error. Without adding anything to it, I get ngsolve and netgen module import failures.

```
[sw23@login2 code]$ echo $PATH
/act/openmpi-2.0/gcc-8.2.0/bin:/vol/apps/gcc/gcc-8.2.0/bin/:/vol/apps/python/3.6.4/bin:/vol/apps/test/ngsolve/gcc-8.2.0/bin:/bin:/usr/lib64/qt-3.3/bin:/home/sw23/perl5/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/act/bin:/act/bin:/act/bin:/home/sw23/.local/bin:/home/sw23/bin
[sw23@login2 code]$ echo $PYTHONPATH
/vol/apps/python/3.6.4/lib/python3.6:/vol/apps/test/ngsolve/gcc-8.2.0/lib/python3.6/site-packages

[sw23@login2 code]$ netgen
NETGEN-6.2-dev
Developed by Joachim Schoeberl at
2010-xxxx Vienna University of Technology
2006-2010 RWTH Aachen University
1996-2006 Johannes Kepler University Linz
Including MPI version 3.1
optfile ./ng.opt does not exist - using default values
togl-version : 2
loading ngsolve library
NGSolve-6.2.1905-21-geb76ec9
Using Lapack
Including sparse direct solver UMFPACK
Running parallel using 20 thread(s)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/vol/apps/test/ngsolve/gcc-8.2.0/lib/python3.6/site-packages/ngsolve/__init__.py", line 12, in <module>
    import netgen
  File "/vol/apps/test/ngsolve/gcc-8.2.0/lib/python3.6/site-packages/netgen/__init__.py", line 6, in <module>
    import tkinter
  File "/vol/apps/python/3.6.4/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/vol/apps/test/ngsolve/gcc-8.2.0/lib/python3.6/site-packages/ngsolve/__init__.py", line 12, in <module>
    import netgen
  File "/vol/apps/test/ngsolve/gcc-8.2.0/lib/python3.6/site-packages/netgen/__init__.py", line 6, in <module>
    import tkinter
  File "/vol/apps/python/3.6.4/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/vol/apps/test/ngsolve/gcc-8.2.0/lib/python3.6/site-packages/netgen/__init__.py", line 6, in <module>
    import tkinter
  File "/vol/apps/python/3.6.4/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
To start the mpi shell call
MpiShell()

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/vol/apps/test/ngsolve/gcc-8.2.0/lib/python3.6/site-packages/ngsolve/__init__.py", line 12, in <module>
    import netgen
  File "/vol/apps/test/ngsolve/gcc-8.2.0/lib/python3.6/site-packages/netgen/__init__.py", line 6, in <module>
    import tkinter
  File "/vol/apps/python/3.6.4/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
Python shell finished.
Thank you for using NGSolve
```
`

**Comment by sw23pdx** [comment]
The reason for the tkinter module error was that Python was not the first entry in the $PATH variable. However, the issue of not being able to load Python scripts, and probably related, it also has ngsolve and netgen import errors, as seen below.

```
[sw23@login1 ~]$ netgen /vol/apps/test/ngsolve/gcc-8.2.0/share/ngsolve/py_tutorials/intro/poisson.py
NETGEN-6.2-dev
Developed by Joachim Schoeberl at
2010-xxxx Vienna University of Technology
2006-2010 RWTH Aachen University
1996-2006 Johannes Kepler University Linz
Including MPI version 3.1
optfile ./ng.opt does not exist - using default values
togl-version : 2
loading ngsolve library
NGSolve-6.2.1905-21-geb76ec9
Using Lapack
Including sparse direct solver UMFPACK
Running parallel using 20 thread(s)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ngsolve'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ngsolve'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
(should) load python file '/vol/apps/test/ngsolve/gcc-8.2.0/share/ngsolve/py_tutorials/intro/poisson.py'
ModuleNotFoundError: No module named 'netgen'
Traceback (most recent call last):
  File "<string>", line 4, in <module>
ModuleNotFoundError: No module named 'ngsolve'
Finished executing /vol/apps/test/ngsolve/gcc-8.2.0/share/ngsolve/py_tutorials/intro/poisson.py
To start the mpi shell call
MpiShell()

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'ngsolve'
Python shell finished.
Thank you for using NGSolve
[sw23@login1 ~]$ # The NGSolve GUI booted with no script loaded, and then the MpiShell() is from me failing to open the Solve > Python shell.
```

**Comment by sw23pdx** [comment]
[sw23@login2 gcc-8.2.0]$ python3 share/ngsolve/py_tutorials/intro/poisson.py
Traceback (most recent call last):
  File "share/ngsolve/py_tutorials/intro/poisson.py", line 4, in <module>
    from ngsolve import *
ModuleNotFoundError: No module named 'ngsolve'

**Comment by mhochsteger** [comment]
As you error message says, your python installation on the cluster is configured without Tk, i.e. without GUI support:
`import _tkinter # If this fails your Python may not be configured for Tk`

Thus, you have to configure NGSolve without GUI, which makes sense in an HPC environment anyway:
`cmake ...your_options... -DUSE_GUI=OFF`

Have a look at the documentation for other cmake configuration options:
https://ngsolve.org/docu/latest/install/cmakeoptions.html
